# Generated by Django 4.2.4 on 2023-12-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ez_backend_test', '0002_alter_customuser_groups_alter_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='store/pdfs/')),
            ],
        ),
    ]
